FROM eclipse-temurin:17-jdk-jammy

# install maven
RUN apt-get update && apt-get install -y maven

WORKDIR /app
COPY . .

RUN mvn clean package -DskipTests

EXPOSE 8080
CMD ["sh", "-c", "java -jar target/*.jar"]