server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:


      # Global CORS configuration (frontend to gateway)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://airline-ticket-frontend.vercel.app/"     # Only your frontend (React) can call backend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      # Route configuration (API Gateway routing logic)
      routes:

        # Auth Service - handles login/register APIs
        - id: auth-service
          uri: https://airlineticket-backend-1.onrender.com
          predicates:
            - Path=/auth/**

        # Flight Service - flight-related APIs
        - id: flight-service
          uri: https://airlineticket-backend-flight-service.onrender.com
          predicates:
            - Path=/flights/**

        # Booking Service - booking APIs
        - id: booking-service
          uri: https://airlineticket-backend-flight-service.onrender.com
          predicates:
            - Path=/bookings/**

        # Passenger Service  - passengers APIs
        - id: passenger-service
          uri: https://airlineticket-backend-1-nlqu.onrender.com
          predicates:
            - Path=/passengers/**

        # Payment Service - payments APIs
        - id: payment-service
          uri: https://airlineticket-backend-payment-service.onrender.com
          predicates:
            - Path=/payments/**

        # Seat Service  seat selection APIs
        - id: seat-service
          uri: https://airlineticket-backend-seat-service.onrender.com
          predicates:
            - Path=/seats/**

        # Airline Service - airline + airport APIs
        - id: airline-service
          uri: https://airlineticket-backend-airline-service.onrender.com
          predicates:
            - Path=/airlines/**,/airports/**

# Actuator (health check & monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
